Change publish workflow - remove version from asset name

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -93,7 +93,6 @@ jobs:
     name: Publish
     needs: prepare
     if: needs.prepare.outputs.status == 'success'
-
     runs-on: ${{ matrix.os }}
     strategy:
       matrix: ${{fromJson(needs.prepare.outputs.matrix)}}
@@ -142,20 +141,41 @@ jobs:
     name: Upload Assets
     if: github.event_name == 'release'
     needs: publish
+    runs-on: ubuntu-latest
     permissions:
       contents: write
 
-    runs-on: ubuntu-latest
+    env:
+      artifacts-root: artifacts
+      assets-root: assets
 
     steps:
     - name: Download All Artifacts
       uses: actions/download-artifact@v4
       with:
-        path: artifacts
+        path: "${{ env.artifacts-root }}"
+
+    - name: Prepare Assets
+      shell: bash
+      run: |
+        asset_root="${{ env.assets-root }}"
+        mkdir -p "${asset_root}"
+
+        artifact_pattern="${{ env.artifacts-root }}/*"
+        for item in $artifact_pattern ; do
+          if [ -d "$item" ] ; then
+            item_name="${item##*/}"
+
+            # remove version
+            asset_name="${item_name% [*}.zip"
+
+            zip -r -j "$asset_root/$asset_name" "$item" && echo "Archiving of the asset '$asset_name' has been completed successfully." || echo "::warning::Failed to archive asset '$asset_name'"
+          fi
+        done
 
     - name: Upload All Assets
       uses: finebits/github-actions/upload-release-asset@v1
       with:
         github-token: ${{ secrets.GITHUB_TOKEN }}
         tag: ${{ github.event.release.tag_name }}
-        path: "artifacts/*"
+        path: "${{ env.assets-root }}/*"
